name: Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: run unit tests
        run: ./gradlew test
